language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
services:
  - postgresql
before_script:
- psql -c "CREATE DATABASE studybuddy;" -U postgres
- psql -c "CREATE USER Matt WITH PASSWORD 'abc123';" -U postgres
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: e8ztKmlVqeLCJ93BNABaxsakmV6PooSEnKFYFSsrPRYXI0MmtI3Or7XtXCZc9Vo3NafimZPo+Yd5vV+CPrQ2V8kJj+8hEoDWqncLPnm85mMk19gtPbfJkY5734n7ATDdIFlNNVA9dA+0PimFYiqySlylsJJdRF1vH1bVxUnGO0LtbeZI9un0fykgIgqiUCm0OkvneflH/126EuG3v9ouJBKWGvH2o4TKLTyLRblI+iwrP6sFc+Ghq9l06Ve47sR4w75oPALRr6AyoF0YxcGVW31+BBUCPv25oiN+vD6lnCqRKr36D0RLnZOc31gq5cGDLPD5pZkSQp4xyqzLf+FD8HZ4oKI3qHJxOyjvMQeN+JUmYzxHBHhNN63ZpT+m+71d2U1HR2+AIBxfL0wj7r5Qz5ipNRHArVHnrIAP/I348iIac+jANWX95ls4YOpvpaZl8BDUTKOPmJ3fILmc3OIUtxDnPxDFDj0ObJsdgTPHXWGQVCNEvKVr4t8e9TpOYeCJwlMLdcHqVGkhDCaxVTCSPeq/DHen/MFTJRFO7c0xlajmhqnjpjjSC7V2e2HRamaPdNkX04TQRjIPV2a3jmOIZyu68Ocj7xr6UWj1nIhQu1qQUMr3dUx6qVKkIo/aTYQJf14bzE4DUgKWQgb7idJkxewgo10QNsWB+MMB28+DRRU=
  on: master
  app: project-103-study-buddy
